//
// Created by lukas on 07.08.20.
//

#ifndef LATTICEMODELIMPLEMENTATIONS_CUBIC_GAUSSIAN_MODEL_HPP
#define LATTICEMODELIMPLEMENTATIONS_CUBIC_GAUSSIAN_MODEL_HPP

#endif //LATTICEMODELIMPLEMENTATIONS_CUBIC_GAUSSIAN_MODEL_HPP
