//
// Created by lukas on 07.08.20.
//

#ifndef LATTICEMODELIMPLEMENTATIONS_SU_TWO_MODEL_HPP
#define LATTICEMODELIMPLEMENTATIONS_SU_TWO_MODEL_HPP

#endif //LATTICEMODELIMPLEMENTATIONS_SU_TWO_MODEL_HPP
