//
// Created by lukas on 07.08.20.
//

#ifndef LATTICEMODELIMPLEMENTATIONS_GLOBAL_UPDATE_HEADER_HPP
#define LATTICEMODELIMPLEMENTATIONS_GLOBAL_UPDATE_HEADER_HPP

#include "global_update_formalisms/hybrid_monte_carlo.hpp"

#endif //LATTICEMODELIMPLEMENTATIONS_GLOBAL_UPDATE_HEADER_HPP
